2025-07-29 15:28:48.717 +01:00 [INF] Now listening on: https://localhost:7235
2025-07-29 15:28:48.783 +01:00 [INF] Now listening on: http://localhost:5058
2025-07-29 15:28:48.786 +01:00 [INF] Application started. Press Ctrl+C to shut down.
2025-07-29 15:28:48.787 +01:00 [INF] Hosting environment: Development
2025-07-29 15:28:48.787 +01:00 [INF] Content root path: C:\Users\kev\projects_vscode\BookStoreApp\BookStoreApp.API
2025-07-29 15:29:00.651 +01:00 [INF] Getting weather forecast
2025-07-29 15:29:00.851 +01:00 [ERR] An error occurred while getting the weather forecast
System.Exception: This is my logging test exception.
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in C:\Users\kev\projects_vscode\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 27
2025-07-29 15:29:01.450 +01:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: This is my logging test exception.
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in C:\Users\kev\projects_vscode\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 27
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-07-29 15:50:36.411 +01:00 [INF] Now listening on: https://localhost:7235
2025-07-29 15:50:36.483 +01:00 [INF] Now listening on: http://localhost:5058
2025-07-29 15:50:36.488 +01:00 [INF] Application started. Press Ctrl+C to shut down.
2025-07-29 15:50:36.488 +01:00 [INF] Hosting environment: Development
2025-07-29 15:50:36.488 +01:00 [INF] Content root path: C:\Users\kev\projects_vscode\BookStoreApp\BookStoreApp.API
2025-07-29 15:52:11.493 +01:00 [INF] Getting weather forecast
2025-07-29 15:52:11.650 +01:00 [ERR] An error occurred while getting the weather forecast
System.Exception: This is my logging test exception.
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in C:\Users\kev\projects_vscode\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 27
2025-07-29 15:52:12.211 +01:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: This is my logging test exception.
   at BookStoreApp.API.Controllers.WeatherForecastController.Get() in C:\Users\kev\projects_vscode\BookStoreApp\BookStoreApp.API\Controllers\WeatherForecastController.cs:line 27
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2025-07-29 18:21:17.648 +01:00 [INF] Now listening on: https://localhost:7235
2025-07-29 18:21:17.738 +01:00 [INF] Now listening on: http://localhost:5058
2025-07-29 18:21:17.744 +01:00 [INF] Application started. Press Ctrl+C to shut down.
2025-07-29 18:21:17.744 +01:00 [INF] Hosting environment: Development
2025-07-29 18:21:17.745 +01:00 [INF] Content root path: C:\Users\kev\projects_vscode\BookStoreApp\BookStoreApp.API
